// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
NOTE: Each deployment takes about {deployment_time} to complete.

=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Ensure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-short-name} AMI

This Quick Start requires a subscription to the AMI for {partner-product-short-name} in AWS Marketplace.

. Sign in to your AWS account.
. {marketplace_listing_url}[Open the page for the {partner-product-short-name} AMI in AWS Marketplace], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page displays, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For more information, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

. Sign in to your AWS account.
. Choose the link provided (*Deploy {partner-product-short-name} into your AWS account*) to launch the AWS CloudFormation template.

[cols=2*]
|===
^|https://fwd.aws/DzxKr[Deploy {partner-product-short-name} into your AWS account.^]
^|https://fwd.aws/qDG9J[View template^]
|===


[start=2]
. The AWS Region that's displayed in the upper-right corner of the navigation bar is where the network infrastructure for {partner-product-short-name} is built. The template is deployed in the {default_deployment_region} Region by default. Change it if necessary.

// *Note:* This deployment includes Amazon EFS, which isn’t currently supported in all AWS Regions. For a current list of supported Regions, see the https://docs.aws.amazon.com/general/latest/gr/elasticfilesystem.html[endpoints and quotas webpage].

[start=3]
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the template parameters and provide values for any parameters that require input. For more information, see the link:#_parameter_reference[Parameter reference] section, later in this guide.

// In the following tables, parameters are listed by category and described separately for the two deployment options:

// * Parameters for deploying {partner-product-short-name} into a new VPC
// * Parameters for deploying {partner-product-short-name} into an existing VPC
