// Add any tips or answers to anticipated questions. This could include the following troubleshooting information. If you don’t have any other Q&A to add, change “FAQ” to “Troubleshooting.”

== FAQ

*Q.* I encountered a *CREATE_FAILED* error when I launched the Quick Start.

*A.* If AWS CloudFormation fails to create the stack, we recommend that you relaunch the template with *Rollback on failure* set to *Disabled*. (This setting is under *Advanced* in the AWS CloudFormation console, *Options* page.) With this setting, the stack’s state is retained and the instance is left running, so you can troubleshoot the issue. (For Windows, look at the log files in %ProgramFiles%\Amazon\EC2ConfigService and C:\cfn\log.)
// If you’re deploying on Linux instances, provide the location for log files on Linux, or omit this sentence.

WARNING: When you set *Rollback on failure* to *Disabled*, you continue to incur AWS charges for this stack. Delete the stack when you finish troubleshooting.

For additional information, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting AWS CloudFormation^] on the AWS website.

*Q.* I encountered a size limitation error when I deployed the AWS CloudFormation templates.

*A.* We recommend that you launch the Quick Start templates from the links in this guide or from another S3 bucket. If you deploy the templates from a local copy on your computer or from a location other than an S3 bucket, you might encounter template size limitations. For more information about AWS CloudFormation quotas, see the http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html[AWS documentation^].

*Q.* How do I get access to Iridium CloudConnect? I already use the
DirectIP channel. How do I get started with a development environment?.

*A.* Customers can connect their development environment to the Iridium
CloudConnect service and use devices of their choice. Iridium expects
most customers to have one Iridium CloudConnect instance for their
development environments and another for their production system, aligning
with the way customers have traditionally set up DirectIP destinations.
Partners can explore Iridium CloudConnect regardless of their existing
connection method to Iridium for SBD®. Please reach out to your channel
manager for a customized technical brief to address your specific
back-end situation and configuration. Most customers have messages
routed to both their traditional method and through Iridium CloudConnect
and use comparative testing to verify operations and utility.

*Q.* What is the pricing for Iridium CloudConnect? Who pays for the AWS
compute resources?

*A.* Iridium is currently not assessing a usage charge for sending
messages through Iridium CloudConnect vs any other method such as
DirectIP. Iridium prefers that customers use Iridium CloudConnect for
development and production environments. As such, Iridium may
direct customers from using SMTP (e-mail) for message exchange to
the SBD gateway for production environment activity.

*Q.* How do you ensure message ordering? Do you use Amazon SQS FIFO (First-In-First-Out)?.

*A.* Iridium processes messages from the gateway in order of receipt but
does not specifically use an AWS Lambda instance for it. Depending on a customer Amazon SQS
queue choice (FIFO or non-FIFO). During the setup of Iridium CloudConnect,
customers can choose the following configurations. FIFO queues will keep
messages in order.